// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addUserToOrganizationStmt, err = db.PrepareContext(ctx, addUserToOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query AddUserToOrganization: %w", err)
	}
	if q.addUserToProjectStmt, err = db.PrepareContext(ctx, addUserToProject); err != nil {
		return nil, fmt.Errorf("error preparing query AddUserToProject: %w", err)
	}
	if q.createOrganizationStmt, err = db.PrepareContext(ctx, createOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrganization: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteOrganizationStmt, err = db.PrepareContext(ctx, deleteOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOrganization: %w", err)
	}
	if q.deleteProjectStmt, err = db.PrepareContext(ctx, deleteProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProject: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserFromOrganizationStmt, err = db.PrepareContext(ctx, deleteUserFromOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserFromOrganization: %w", err)
	}
	if q.deleteUserFromProjectStmt, err = db.PrepareContext(ctx, deleteUserFromProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserFromProject: %w", err)
	}
	if q.getAllOrganizationsByUserStmt, err = db.PrepareContext(ctx, getAllOrganizationsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllOrganizationsByUser: %w", err)
	}
	if q.getAllUsersInOrganizationStmt, err = db.PrepareContext(ctx, getAllUsersInOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsersInOrganization: %w", err)
	}
	if q.getAllUsersInProjectStmt, err = db.PrepareContext(ctx, getAllUsersInProject); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsersInProject: %w", err)
	}
	if q.getOrganizationByEmailStmt, err = db.PrepareContext(ctx, getOrganizationByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationByEmail: %w", err)
	}
	if q.getOrganizationByIDStmt, err = db.PrepareContext(ctx, getOrganizationByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationByID: %w", err)
	}
	if q.getOrganizationOwnerStmt, err = db.PrepareContext(ctx, getOrganizationOwner); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrganizationOwner: %w", err)
	}
	if q.getProjectByIDStmt, err = db.PrepareContext(ctx, getProjectByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectByID: %w", err)
	}
	if q.getProjectByNameStmt, err = db.PrepareContext(ctx, getProjectByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectByName: %w", err)
	}
	if q.getProjectOwnerStmt, err = db.PrepareContext(ctx, getProjectOwner); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectOwner: %w", err)
	}
	if q.getProjectsByOrganizationStmt, err = db.PrepareContext(ctx, getProjectsByOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectsByOrganization: %w", err)
	}
	if q.getProjectsByUserStmt, err = db.PrepareContext(ctx, getProjectsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectsByUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserRoleInProjectStmt, err = db.PrepareContext(ctx, getUserRoleInProject); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRoleInProject: %w", err)
	}
	if q.updateOrganizationStmt, err = db.PrepareContext(ctx, updateOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrganization: %w", err)
	}
	if q.updateProjectStmt, err = db.PrepareContext(ctx, updateProject); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProject: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserInOrganizationStmt, err = db.PrepareContext(ctx, updateUserInOrganization); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserInOrganization: %w", err)
	}
	if q.updateUserInProjectStmt, err = db.PrepareContext(ctx, updateUserInProject); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserInProject: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addUserToOrganizationStmt != nil {
		if cerr := q.addUserToOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserToOrganizationStmt: %w", cerr)
		}
	}
	if q.addUserToProjectStmt != nil {
		if cerr := q.addUserToProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserToProjectStmt: %w", cerr)
		}
	}
	if q.createOrganizationStmt != nil {
		if cerr := q.createOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrganizationStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteOrganizationStmt != nil {
		if cerr := q.deleteOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOrganizationStmt: %w", cerr)
		}
	}
	if q.deleteProjectStmt != nil {
		if cerr := q.deleteProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProjectStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserFromOrganizationStmt != nil {
		if cerr := q.deleteUserFromOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserFromOrganizationStmt: %w", cerr)
		}
	}
	if q.deleteUserFromProjectStmt != nil {
		if cerr := q.deleteUserFromProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserFromProjectStmt: %w", cerr)
		}
	}
	if q.getAllOrganizationsByUserStmt != nil {
		if cerr := q.getAllOrganizationsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllOrganizationsByUserStmt: %w", cerr)
		}
	}
	if q.getAllUsersInOrganizationStmt != nil {
		if cerr := q.getAllUsersInOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersInOrganizationStmt: %w", cerr)
		}
	}
	if q.getAllUsersInProjectStmt != nil {
		if cerr := q.getAllUsersInProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersInProjectStmt: %w", cerr)
		}
	}
	if q.getOrganizationByEmailStmt != nil {
		if cerr := q.getOrganizationByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationByEmailStmt: %w", cerr)
		}
	}
	if q.getOrganizationByIDStmt != nil {
		if cerr := q.getOrganizationByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationByIDStmt: %w", cerr)
		}
	}
	if q.getOrganizationOwnerStmt != nil {
		if cerr := q.getOrganizationOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrganizationOwnerStmt: %w", cerr)
		}
	}
	if q.getProjectByIDStmt != nil {
		if cerr := q.getProjectByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectByIDStmt: %w", cerr)
		}
	}
	if q.getProjectByNameStmt != nil {
		if cerr := q.getProjectByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectByNameStmt: %w", cerr)
		}
	}
	if q.getProjectOwnerStmt != nil {
		if cerr := q.getProjectOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectOwnerStmt: %w", cerr)
		}
	}
	if q.getProjectsByOrganizationStmt != nil {
		if cerr := q.getProjectsByOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectsByOrganizationStmt: %w", cerr)
		}
	}
	if q.getProjectsByUserStmt != nil {
		if cerr := q.getProjectsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectsByUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserRoleInProjectStmt != nil {
		if cerr := q.getUserRoleInProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRoleInProjectStmt: %w", cerr)
		}
	}
	if q.updateOrganizationStmt != nil {
		if cerr := q.updateOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrganizationStmt: %w", cerr)
		}
	}
	if q.updateProjectStmt != nil {
		if cerr := q.updateProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserInOrganizationStmt != nil {
		if cerr := q.updateUserInOrganizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserInOrganizationStmt: %w", cerr)
		}
	}
	if q.updateUserInProjectStmt != nil {
		if cerr := q.updateUserInProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserInProjectStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	addUserToOrganizationStmt      *sql.Stmt
	addUserToProjectStmt           *sql.Stmt
	createOrganizationStmt         *sql.Stmt
	createProjectStmt              *sql.Stmt
	createUserStmt                 *sql.Stmt
	deleteOrganizationStmt         *sql.Stmt
	deleteProjectStmt              *sql.Stmt
	deleteUserStmt                 *sql.Stmt
	deleteUserFromOrganizationStmt *sql.Stmt
	deleteUserFromProjectStmt      *sql.Stmt
	getAllOrganizationsByUserStmt  *sql.Stmt
	getAllUsersInOrganizationStmt  *sql.Stmt
	getAllUsersInProjectStmt       *sql.Stmt
	getOrganizationByEmailStmt     *sql.Stmt
	getOrganizationByIDStmt        *sql.Stmt
	getOrganizationOwnerStmt       *sql.Stmt
	getProjectByIDStmt             *sql.Stmt
	getProjectByNameStmt           *sql.Stmt
	getProjectOwnerStmt            *sql.Stmt
	getProjectsByOrganizationStmt  *sql.Stmt
	getProjectsByUserStmt          *sql.Stmt
	getUserByEmailStmt             *sql.Stmt
	getUserByIDStmt                *sql.Stmt
	getUserRoleInProjectStmt       *sql.Stmt
	updateOrganizationStmt         *sql.Stmt
	updateProjectStmt              *sql.Stmt
	updateUserStmt                 *sql.Stmt
	updateUserInOrganizationStmt   *sql.Stmt
	updateUserInProjectStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		addUserToOrganizationStmt:      q.addUserToOrganizationStmt,
		addUserToProjectStmt:           q.addUserToProjectStmt,
		createOrganizationStmt:         q.createOrganizationStmt,
		createProjectStmt:              q.createProjectStmt,
		createUserStmt:                 q.createUserStmt,
		deleteOrganizationStmt:         q.deleteOrganizationStmt,
		deleteProjectStmt:              q.deleteProjectStmt,
		deleteUserStmt:                 q.deleteUserStmt,
		deleteUserFromOrganizationStmt: q.deleteUserFromOrganizationStmt,
		deleteUserFromProjectStmt:      q.deleteUserFromProjectStmt,
		getAllOrganizationsByUserStmt:  q.getAllOrganizationsByUserStmt,
		getAllUsersInOrganizationStmt:  q.getAllUsersInOrganizationStmt,
		getAllUsersInProjectStmt:       q.getAllUsersInProjectStmt,
		getOrganizationByEmailStmt:     q.getOrganizationByEmailStmt,
		getOrganizationByIDStmt:        q.getOrganizationByIDStmt,
		getOrganizationOwnerStmt:       q.getOrganizationOwnerStmt,
		getProjectByIDStmt:             q.getProjectByIDStmt,
		getProjectByNameStmt:           q.getProjectByNameStmt,
		getProjectOwnerStmt:            q.getProjectOwnerStmt,
		getProjectsByOrganizationStmt:  q.getProjectsByOrganizationStmt,
		getProjectsByUserStmt:          q.getProjectsByUserStmt,
		getUserByEmailStmt:             q.getUserByEmailStmt,
		getUserByIDStmt:                q.getUserByIDStmt,
		getUserRoleInProjectStmt:       q.getUserRoleInProjectStmt,
		updateOrganizationStmt:         q.updateOrganizationStmt,
		updateProjectStmt:              q.updateProjectStmt,
		updateUserStmt:                 q.updateUserStmt,
		updateUserInOrganizationStmt:   q.updateUserInOrganizationStmt,
		updateUserInProjectStmt:        q.updateUserInProjectStmt,
	}
}
