// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: envs.queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnv = `-- name: CreateEnv :one
INSERT INTO envs (name, project_id, variables, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, project_id, variables, version, description, created_by, created_at, updated_at
`

type CreateEnvParams struct {
	Name        string          `json:"name"`
	ProjectID   uuid.UUID       `json:"project_id"`
	Variables   json.RawMessage `json:"variables"`
	Description string          `json:"description"`
	CreatedBy   uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateEnv(ctx context.Context, arg CreateEnvParams) (Envs, error) {
	row := q.db.QueryRow(ctx, createEnv,
		arg.Name,
		arg.ProjectID,
		arg.Variables,
		arg.Description,
		arg.CreatedBy,
	)
	var i Envs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Variables,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnv = `-- name: DeleteEnv :exec
DELETE FROM envs
WHERE id = $1
`

func (q *Queries) DeleteEnv(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnv, id)
	return err
}

const getEnvByID = `-- name: GetEnvByID :one
SELECT id, name, project_id, variables, version, description, created_by, created_at, updated_at FROM envs
WHERE id = $1
`

func (q *Queries) GetEnvByID(ctx context.Context, id uuid.UUID) (Envs, error) {
	row := q.db.QueryRow(ctx, getEnvByID, id)
	var i Envs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Variables,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvByNameInProject = `-- name: GetEnvByNameInProject :one
SELECT id, name, project_id, variables, version, description, created_by, created_at, updated_at FROM envs
WHERE name = $1 AND project_id = $2
`

type GetEnvByNameInProjectParams struct {
	Name      string    `json:"name"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetEnvByNameInProject(ctx context.Context, arg GetEnvByNameInProjectParams) (Envs, error) {
	row := q.db.QueryRow(ctx, getEnvByNameInProject, arg.Name, arg.ProjectID)
	var i Envs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Variables,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvsByProject = `-- name: GetEnvsByProject :many
SELECT id, name, project_id, variables, version, description, created_by, created_at, updated_at FROM envs
WHERE project_id = $1
`

func (q *Queries) GetEnvsByProject(ctx context.Context, projectID uuid.UUID) ([]Envs, error) {
	rows, err := q.db.Query(ctx, getEnvsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Envs
	for rows.Next() {
		var i Envs
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.Variables,
			&i.Version,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnv = `-- name: UpdateEnv :one
UPDATE envs
SET 
  name = COALESCE($1, name),
  variables = COALESCE($2, variables),
  description = COALESCE($3, description),
  version = version + 1,
  updated_at = NOW()
WHERE id = $4
RETURNING id, name, project_id, variables, version, description, created_by, created_at, updated_at
`

type UpdateEnvParams struct {
	Name        pgtype.Text `json:"name"`
	Variables   []byte      `json:"variables"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEnv(ctx context.Context, arg UpdateEnvParams) (Envs, error) {
	row := q.db.QueryRow(ctx, updateEnv,
		arg.Name,
		arg.Variables,
		arg.Description,
		arg.ID,
	)
	var i Envs
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Variables,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
