// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role string

const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
	RoleOwner  Role = "owner"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Envs struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Variables   json.RawMessage    `json:"variables"`
	Version     int32              `json:"version"`
	Description string             `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMembers struct {
	UserID         uuid.UUID          `json:"user_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Role           Role               `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organizations struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Email     string             `json:"email"`
	Passkey   string             `json:"passkey"`
}

type ProjectMembers struct {
	UserID    uuid.UUID          `json:"user_id"`
	ProjectID uuid.UUID          `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      interface{}        `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type Projects struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Passkey        string             `json:"passkey"`
	CreatedBy      uuid.UUID          `json:"created_by"`
}

type Users struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Name      string             `json:"name"`
}
