// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToOrganization = `-- name: AddUserToOrganization :one
INSERT INTO organization_members (user_id,organization_id,role)
VALUES ($1,$2,$3)
RETURNING user_id, organization_id, role, created_at, updated_at
`

type AddUserToOrganizationParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           Role        `json:"role"`
}

func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (OrganizationMembers, error) {
	row := q.db.QueryRow(ctx, addUserToOrganization, arg.UserID, arg.OrganizationID, arg.Role)
	var i OrganizationMembers
	err := row.Scan(
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name,email,passkey,created_by) 
VALUES ($1,$2,$3,$4)
RETURNING id,name,email
`

type CreateOrganizationParams struct {
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Passkey   string      `json:"passkey"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type CreateOrganizationRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Email,
		arg.Passkey,
		arg.CreatedBy,
	)
	var i CreateOrganizationRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const deleteUserFromOrganization = `-- name: DeleteUserFromOrganization :exec
DELETE FROM organization_members 
WHERE user_id = $1 AND organization_id = $2
`

type DeleteUserFromOrganizationParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteUserFromOrganization(ctx context.Context, arg DeleteUserFromOrganizationParams) error {
	_, err := q.db.Exec(ctx, deleteUserFromOrganization, arg.UserID, arg.OrganizationID)
	return err
}

const getAllOrganizationsByUser = `-- name: GetAllOrganizationsByUser :many
SELECT o.id,o.name,o.email,o.passkey FROM organizations o 
INNER JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1
`

type GetAllOrganizationsByUserRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Email   string      `json:"email"`
	Passkey string      `json:"passkey"`
}

func (q *Queries) GetAllOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]GetAllOrganizationsByUserRow, error) {
	rows, err := q.db.Query(ctx, getAllOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrganizationsByUserRow
	for rows.Next() {
		var i GetAllOrganizationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Passkey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersInOrganization = `-- name: GetAllUsersInOrganization :many
SELECT u.id,u.name,u.email FROM users u 
INNER JOIN organization_members om ON om.user_id = u.id
WHERE om.organization_id = $1
`

type GetAllUsersInOrganizationRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
}

func (q *Queries) GetAllUsersInOrganization(ctx context.Context, organizationID pgtype.UUID) ([]GetAllUsersInOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getAllUsersInOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersInOrganizationRow
	for rows.Next() {
		var i GetAllUsersInOrganizationRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByEmail = `-- name: GetOrganizationByEmail :one
SELECT id,name,email,created_by FROM organizations
WHERE email = $1
`

type GetOrganizationByEmailRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) GetOrganizationByEmail(ctx context.Context, email string) (GetOrganizationByEmailRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByEmail, email)
	var i GetOrganizationByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedBy,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id,name,email,created_by FROM organizations
WHERE id = $1
`

type GetOrganizationByIDRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (GetOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i GetOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedBy,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT id,name,email,created_by FROM organizations
WHERE name = $1
`

type GetOrganizationByNameRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (GetOrganizationByNameRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByName, name)
	var i GetOrganizationByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedBy,
	)
	return i, err
}

const getOrganizationOwner = `-- name: GetOrganizationOwner :one
SELECT u.id,u.email,u.name FROM users u
INNER JOIN organizations o ON o.created_by = u.id
WHERE o.id = $1
`

type GetOrganizationOwnerRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) GetOrganizationOwner(ctx context.Context, id pgtype.UUID) (GetOrganizationOwnerRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationOwner, id)
	var i GetOrganizationOwnerRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET 
  name = COALESCE($1, name),
  email = COALESCE($2, email),
  passkey = COALESCE($3, passkey),
  updated_at = NOW()
WHERE id = $4
RETURNING id,name,email
`

type UpdateOrganizationParams struct {
	Name    pgtype.Text `json:"name"`
	Email   pgtype.Text `json:"email"`
	Passkey pgtype.Text `json:"passkey"`
	ID      pgtype.UUID `json:"id"`
}

type UpdateOrganizationRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Name,
		arg.Email,
		arg.Passkey,
		arg.ID,
	)
	var i UpdateOrganizationRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const updateUserInOrganization = `-- name: UpdateUserInOrganization :one
UPDATE organization_members
SET 
  role = COALESCE($3, role)
WHERE user_id = $1 AND organization_id = $2
RETURNING role
`

type UpdateUserInOrganizationParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Role           NullRole    `json:"role"`
}

func (q *Queries) UpdateUserInOrganization(ctx context.Context, arg UpdateUserInOrganizationParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateUserInOrganization, arg.UserID, arg.OrganizationID, arg.Role)
	var role Role
	err := row.Scan(&role)
	return role, err
}
