// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToProject = `-- name: AddUserToProject :one
INSERT INTO project_members (user_id, project_id, role)
VALUES ($1, $2, $3)
RETURNING user_id, project_id, created_at, updated_at, role, joined_at
`

type AddUserToProjectParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Role      interface{} `json:"role"`
}

func (q *Queries) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) (ProjectMembers, error) {
	row := q.db.QueryRow(ctx, addUserToProject, arg.UserID, arg.ProjectID, arg.Role)
	var i ProjectMembers
	err := row.Scan(
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, passkey, organization_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, organization_id, created_at
`

type CreateProjectParams struct {
	Name           string      `json:"name"`
	Passkey        string      `json:"passkey"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

type CreateProjectRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Passkey,
		arg.OrganizationID,
		arg.CreatedBy,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteUserFromProject = `-- name: DeleteUserFromProject :exec
DELETE FROM project_members
WHERE user_id = $1 AND project_id = $2
`

type DeleteUserFromProjectParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteUserFromProject(ctx context.Context, arg DeleteUserFromProjectParams) error {
	_, err := q.db.Exec(ctx, deleteUserFromProject, arg.UserID, arg.ProjectID)
	return err
}

const getAllUsersInProject = `-- name: GetAllUsersInProject :many
SELECT u.id, u.name, u.email, pm.role, pm.joined_at
FROM users u
INNER JOIN project_members pm ON pm.user_id = u.id
WHERE pm.project_id = $1
`

type GetAllUsersInProjectRow struct {
	ID       pgtype.UUID        `json:"id"`
	Name     string             `json:"name"`
	Email    string             `json:"email"`
	Role     interface{}        `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetAllUsersInProject(ctx context.Context, projectID pgtype.UUID) ([]GetAllUsersInProjectRow, error) {
	rows, err := q.db.Query(ctx, getAllUsersInProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersInProjectRow
	for rows.Next() {
		var i GetAllUsersInProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, organization_id, created_by, created_at
FROM projects
WHERE id = $1
`

type GetProjectByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, organization_id, created_by, created_at
FROM projects
WHERE name = $1 AND organization_id = $2
`

type GetProjectByNameParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetProjectByNameRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (GetProjectByNameRow, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.Name, arg.OrganizationID)
	var i GetProjectByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectOwner = `-- name: GetProjectOwner :one
SELECT u.id, u.email, u.name FROM users u
INNER JOIN projects p ON p.created_by = u.id
WHERE p.id = $1
`

type GetProjectOwnerRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) GetProjectOwner(ctx context.Context, id pgtype.UUID) (GetProjectOwnerRow, error) {
	row := q.db.QueryRow(ctx, getProjectOwner, id)
	var i GetProjectOwnerRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const getProjectsByOrganization = `-- name: GetProjectsByOrganization :many
SELECT id, name, organization_id, created_by, created_at
FROM projects
WHERE organization_id = $1
`

type GetProjectsByOrganizationRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProjectsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]GetProjectsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsByOrganizationRow
	for rows.Next() {
		var i GetProjectsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByUser = `-- name: GetProjectsByUser :many
SELECT p.id, p.name, p.organization_id, p.created_by, p.created_at, pm.role
FROM projects p
INNER JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
`

type GetProjectsByUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Role           interface{}        `json:"role"`
}

func (q *Queries) GetProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]GetProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, getProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsByUserRow
	for rows.Next() {
		var i GetProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleInProject = `-- name: GetUserRoleInProject :one
SELECT role FROM project_members
WHERE user_id = $1 AND project_id = $2
`

type GetUserRoleInProjectParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetUserRoleInProject(ctx context.Context, arg GetUserRoleInProjectParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getUserRoleInProject, arg.UserID, arg.ProjectID)
	var role interface{}
	err := row.Scan(&role)
	return role, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name       = COALESCE($1, name),
    passkey    = COALESCE($2, passkey),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, organization_id, updated_at
`

type UpdateProjectParams struct {
	Name    pgtype.Text `json:"name"`
	Passkey pgtype.Text `json:"passkey"`
	ID      pgtype.UUID `json:"id"`
}

type UpdateProjectRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.Passkey, arg.ID)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserInProject = `-- name: UpdateUserInProject :one
UPDATE project_members
SET role = COALESCE($3, role)
WHERE user_id = $1 AND project_id = $2
RETURNING role
`

type UpdateUserInProjectParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Role      interface{} `json:"role"`
}

func (q *Queries) UpdateUserInProject(ctx context.Context, arg UpdateUserInProjectParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateUserInProject, arg.UserID, arg.ProjectID, arg.Role)
	var role interface{}
	err := row.Scan(&role)
	return role, err
}
