// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (OrganizationMembers, error)
	AddUserToProject(ctx context.Context, arg AddUserToProjectParams) (ProjectMembers, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserFromOrganization(ctx context.Context, arg DeleteUserFromOrganizationParams) error
	DeleteUserFromProject(ctx context.Context, arg DeleteUserFromProjectParams) error
	GetAllOrganizationsByUser(ctx context.Context, userID uuid.UUID) ([]GetAllOrganizationsByUserRow, error)
	GetAllUsersInOrganization(ctx context.Context, organizationID uuid.UUID) ([]GetAllUsersInOrganizationRow, error)
	GetAllUsersInProject(ctx context.Context, projectID uuid.UUID) ([]GetAllUsersInProjectRow, error)
	GetOrganizationByEmail(ctx context.Context, email string) (GetOrganizationByEmailRow, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (GetOrganizationByIDRow, error)
	GetOrganizationOwner(ctx context.Context, id uuid.UUID) (GetOrganizationOwnerRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (GetProjectByIDRow, error)
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (GetProjectByNameRow, error)
	GetProjectOwner(ctx context.Context, id uuid.UUID) (GetProjectOwnerRow, error)
	GetProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]GetProjectsByOrganizationRow, error)
	GetProjectsByUser(ctx context.Context, userID uuid.UUID) ([]GetProjectsByUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserRoleInProject(ctx context.Context, arg GetUserRoleInProjectParams) (interface{}, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserInOrganization(ctx context.Context, arg UpdateUserInOrganizationParams) (Role, error)
	UpdateUserInProject(ctx context.Context, arg UpdateUserInProjectParams) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
